"""Execution check for the training cell's saliency loss (Pending 10).

Runs 7-8 had exactly one new, unverified cell -- cell 11, the training loop -- and that
is where D4 and D5 both found bugs. `verify_selection_ablation.py` covers cells 4/7/15
(44/44) and the cell-hash diff shows those transferred byte-identically to the derived
notebook, so cell 11 was the whole gap. This closes it.

Convention (same as every other verifier here): assert a value the CORRECT
implementation must produce, not that the code runs. The saliency block is EXTRACTED
FROM THE NOTEBOOK AND EXECUTED, never paraphrased -- a paraphrase would verify this
file instead of the thing that runs on Kaggle.

Eight assertion groups (11 checks):

  A SOLVED       scores equal to the target must drive the saliency term to ~0.
                 A loss that cannot be satisfied cannot say "this token is done".
  B ORDERED      inverted scores must cost strictly more than matched scores.
                 (This one passes even with the D4 bug -- sigmoid is monotone, which is
                 why run 8's sign-fix worked at all. Kept as a regression guard.)
  C PROPORTIONAL |d_sal/dz| must be proportional to |p - t|, where z is the scorer's
                 pre-sigmoid activation. For a correctly specified BCE this ratio is
                 exactly 1.0 at every score. This is the assertion that catches D4.
  D EXPLICIT     every `lambda_*` of AdaptivePruningLoss must be passed explicitly at
                 every construction site. D5: `lambda_entropy=0.05` shaped run 8 while
                 appearing in no config cell, because cell 11 never passed it.
  E RANGE        the router's `scores` must lie in (0,1), because loss.py's sparsity
                 term reads their mean as a fraction and its entropy term clamps them
                 to (0,1). This is the contract that makes D4's ORIGINAL proposed fix
                 (return the pre-sigmoid logit) fail loudly instead of silently.
  F PARITY       kaggle_pruning_run.ipynb is GENERATED by
                 scripts/make_kaggle_pruning_notebook.py. The loss line must match in
                 both, or the next regeneration silently reverts the fix.
  G CONTENT-ONLY (added 2026-09-02 for Pending 13(b)) the ATTN and INK branches must
                 produce a BIT-IDENTICAL `_sal` when handed the same target. D7's
                 requirement was to keep the SHAPE of the ink term and change only what
                 it points at; without this check "I only changed the target" is a claim
                 about intent rather than a property of the code.
  H GUARD        (added 2026-09-02) the step-0 degeneracy guard, run against BOTH states
                 plus a valid one: an all-zero and an all-one target must RAISE on the
                 ATTN branch, a real top-K target must pass, and a degenerate INK target
                 must only WARN -- because a legal all-blank first page must not add a
                 new fatal path to the branch that already produced run 9. A guard is
                 half-tested until it has been driven against the state it must accept.

Usage:
    PYTHONIOENCODING=utf-8 PYTHONPATH=. python scripts/verify_saliency_loss_cell.py
Exit code 0 iff all of them pass.
"""
import ast
import json
import os
import re
import sys
import textwrap

import torch
import torch.nn.functional as F

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

NB = os.path.join(ROOT, "kaggle_pruning_run.ipynb")
GEN = os.path.join(ROOT, "scripts", "make_kaggle_pruning_notebook.py")
LOSS_PY = os.path.join(ROOT, "src", "loss.py")
SALIENCY_THRESHOLD = 0.15          # cell 2
TOL_SOLVED = 0.05                  # "~0" for a satisfiable loss
TOL_SPREAD = 1.5                   # allowed spread in the grad/error ratio

results = []


def check(name, ok, detail):
    results.append((name, ok, detail))
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}: {detail}")


# ------------------------------------------------------- extract the block, verbatim
def cell11(path):
    cells = ["".join(c["source"]) for c in json.load(open(path, encoding="utf-8"))["cells"]]
    return cells[11]


def extract_saliency_block(src):
    """The lines between `_sc = outputs['scores']` and the `loss = loss +` that uses it.

    Returned dedented and unmodified. Raises if the shape of the block changed, so this
    verifier goes stale loudly rather than silently checking nothing.
    """
    lines = src.splitlines()
    start = next((i for i, l in enumerate(lines) if l.strip().startswith("_sc = outputs[")), None)
    if start is None:
        raise SystemExit("could not find `_sc = outputs['scores']` in cell 11 -- "
                         "the saliency block moved or was removed; re-derive this verifier")
    end = next((i for i in range(start, len(lines))
                if lines[i].strip().startswith("loss = loss +")), None)
    if end is None:
        raise SystemExit("found the saliency block but not the `loss = loss +` that consumes it")
    block = textwrap.dedent("\n".join(lines[start:end]))
    ast.parse(block)
    return block


nb_src = cell11(NB)
block = extract_saliency_block(nb_src)
print("=" * 78)
print("saliency block EXTRACTED FROM kaggle_pruning_run.ipynb cell 11 (executed as-is)")
print("=" * 78)
for l in block.splitlines():
    print(f"  | {l}")
print()


def run_block(p, tgt, attn_target=False, teacher=None):
    """Execute the extracted block with a controlled score tensor and ink target.

    `patch_ink` is stubbed to hand back exactly the ink pattern that makes the block's
    own `_tgt = (_inkn > SALIENCY_THRESHOLD)` come out as `tgt`, so the block's target
    construction is exercised rather than bypassed.

    `step`/`epoch` are bound to 0/1 deliberately, so 13(b)'s degeneracy assert RUNS here
    instead of being dead code in this harness -- case F below relies on it firing.
    `attn_target=True` takes the 13(b) branch with a stubbed `attn_topk_target`, which is
    how case E shows the branch changes the target's CONTENT and nothing about the math.
    """
    ink = tgt.clone()                      # amax-normalized ink of 1.0/0.0 -> tgt as-is
    ns = {
        "torch": torch, "F": F,
        "outputs": {"scores": p.unsqueeze(-1), "visual_tokens": None},
        "pixel_values": None,
        "patch_ink": lambda pv, n: ink,
        "SALIENCY_THRESHOLD": SALIENCY_THRESHOLD,
        # 13(b) added `if ATTN_TARGET:` to this block. These four names live in cell 2 and
        # the training loop on Kaggle; this harness has to supply them or it NameErrors --
        # which is exactly how it failed when the branch first landed.
        "ATTN_TARGET": attn_target,
        "TRAIN_KEEP_RATIO": 0.50,
        "step": 0, "epoch": 1,
        "attn_topk_target": teacher,
        "_teacher_dec": object(),
        "decoder_input_ids": None, "labels": None,
    }
    exec(compile(block, "<cell11-saliency>", "exec"), ns)
    assert torch.equal(ns["_tgt"], tgt), "stub failed: block's _tgt != requested target"
    return ns["_sal"]


# ------------------------------------------------------------------------ A  SOLVED
print("=" * 78)
print("ASSERTIONS")
print("=" * 78)
tgt = torch.tensor([[1.0, 1.0, 0.0, 0.0]])
matched = run_block(tgt.clone(), tgt)          # scores == target, exactly
check("A SOLVED", float(matched) < TOL_SOLVED,
      f"_sal on perfectly-matched scores = {float(matched):.4f} (want < {TOL_SOLVED}); "
      f"a satisfiable BCE reaches ~0")

# ------------------------------------------------------------------------ B  ORDERED
inverted = run_block(1.0 - tgt, tgt)
check("B ORDERED", float(inverted) > float(matched) + 1e-6,
      f"inverted {float(inverted):.4f} > matched {float(matched):.4f} "
      f"(monotone ranking still learnable)")

# ------------------------------------------------------------------- C  PROPORTIONAL
# z is the scorer's pre-sigmoid activation; p = sigmoid(z) is what the router returns.
# A correctly specified BCE gives d(BCE)/dz == p - t exactly, so the ratio below is 1.0
# at every score. Anything else means the loss is loudest in the wrong places.
ratios = []
for pv, tv in ((0.02, 1.0), (0.20, 1.0), (0.50, 1.0), (0.98, 1.0), (0.02, 0.0), (0.98, 0.0)):
    z = torch.tensor([[float(torch.logit(torch.tensor(pv)))]], requires_grad=True)
    sal = run_block(torch.sigmoid(z), torch.tensor([[tv]]))
    sal.backward()
    ratios.append((pv, tv, abs(float(z.grad)) / abs(pv - tv)))
spread = max(r for *_, r in ratios) / max(min(r for *_, r in ratios), 1e-12)
print(f"         {'p':>6} {'t':>4} {'|d_sal/dz| / |p-t|':>20}")
for pv, tv, r in ratios:
    print(f"         {pv:6.2f} {tv:4.0f} {r:20.4f}")
worst = min(ratios, key=lambda x: x[2])
best = max(ratios, key=lambda x: x[2])
check("C PROPORTIONAL", spread < TOL_SPREAD,
      f"spread {spread:.1f}x (want < {TOL_SPREAD}x). Weakest at p={worst[0]}/t={worst[1]:.0f} "
      f"({worst[2]:.4f}), strongest at p={best[0]}/t={best[1]:.0f} ({best[2]:.4f})")

# ------------------------------------------------- E  13(b) BRANCH IS CONTENT-ONLY
# D7's requirement for a replacement target was "change only the content" -- keep the ink
# term's shape (dense / coherent / free) and swap what it points at. That is checkable:
# feed the ATTN_TARGET branch a stub returning the SAME tensor the ink branch built, and
# the resulting _sal must be bit-identical. If it is not, the branch touched the math.
attn_same = run_block(tgt.clone(), tgt, attn_target=True,
                      teacher=lambda *a, **k: tgt.clone())
check("G CONTENT-ONLY", torch.equal(attn_same, matched),
      f"ATTN branch _sal {float(attn_same):.6f} == INK branch _sal {float(matched):.6f} "
      f"on an identical target, so 13(b) changed the target and not the loss")

# ------------------------------------------------------ F  DEGENERACY ASSERT FIRES
# The guard is only half-tested until it has run against both states. An all-zero target
# teaches the router a constant and the run completes and is void. The guard lives on the
# ATTN branch, where top-K makes the rate exactly K/N so the check cannot misfire on page
# content; the INK branch only warns, because one legitimately blank first page must not
# kill a 4-hour run. (The first version of this assert was `0 < rate < 1` on both branches
# and case C below caught it: a single-element target is legally rate 1.0.)
# `step`/`epoch` are bound to 0/1 in run_block precisely so this path is live.
for label, bad in (("all-zero", torch.zeros_like(tgt)), ("all-one", torch.ones_like(tgt))):
    try:
        run_block(tgt.clone(), bad, attn_target=True, teacher=lambda *a, **k: bad.clone())
        check(f"H GUARD FIRES ({label})", False,
              f"a {label} attention target did NOT raise -- the guard is decorative")
    except AssertionError as e:
        check(f"H GUARD FIRES ({label})", "positive rate" in str(e),
              f"{label} raises: {str(e)[:56]}")
# ...and it must NOT fire on a real top-K target, or every 13(b) run dies at step 0.
try:
    ok_rate = run_block(tgt.clone(), tgt, attn_target=True,
                        teacher=lambda *a, **k: tgt.clone())
    check("H GUARD PASSES a real top-K target", True,
          f"rate 0.5 == K/N ran clean (_sal {float(ok_rate):.4f})")
except AssertionError as e:
    check("H GUARD PASSES a real top-K target", False,
          f"fires on a VALID target -- every 13(b) run would die at step 0: {str(e)[:44]}")
# INK's degenerate case must WARN, not raise -- it is run 9's path and gains no new way to die.
try:
    run_block(tgt.clone(), torch.zeros_like(tgt))
    check("H INK degenerate warns, does not raise", True,
          "all-blank first page survives on the ink path")
except AssertionError as e:
    check("H INK degenerate warns, does not raise", False,
          f"regression: run 9's path now dies on a blank page: {str(e)[:44]}")

# ---------------------------------------------------------------------- D  EXPLICIT
# The notebook carries its OWN copy of AdaptivePruningLoss (cell 5) and imports nothing
# from src/ -- see the duplication gotcha. Read the parameter names from the copy that
# actually runs, and assert all three copies still agree, since a defaults drift between
# them would make Kaggle rows silently non-comparable to local ones.
loss_src = open(LOSS_PY, encoding="utf-8").read()


def init_defaults(src):
    for n in ast.walk(ast.parse(src)):
        if isinstance(n, ast.ClassDef) and n.name == "AdaptivePruningLoss":
            for f in n.body:
                if isinstance(f, ast.FunctionDef) and f.name == "__init__":
                    args = [a.arg for a in f.args.args][1:]
                    defs = [ast.unparse(d) for d in f.args.defaults]
                    return dict(zip(args[-len(defs):], defs)) if defs else {}
    return None


nb_cell5 = "".join(json.load(open(NB, encoding="utf-8"))["cells"][5]["source"])
d_nb, d_src = init_defaults(nb_cell5), init_defaults(loss_src)
copies_agree = d_nb == d_src
lambdas = [k for k in (d_nb or {}) if k.startswith("lambda_")]
sites = re.findall(r"AdaptivePruningLoss\(([^)]*)\)", nb_src, re.S)
missing = {}
for i, args in enumerate(sites):
    flat = re.sub(r"\s+", "", args)
    absent = [k for k in lambdas if k + "=" not in flat]
    if absent:
        missing[i] = absent
check("D EXPLICIT", not missing and copies_agree and len(sites) > 0,
      f"{len(sites)} construction site(s), lambdas {lambdas}, notebook/src defaults "
      f"agree={copies_agree}; "
      + ("all passed explicitly" if not missing
         else f"DEFAULTED (invisible in the notebook): {missing}"))

# ------------------------------------------------------------------------- E  RANGE
from src.router import PatchSaliencyRouter        # noqa: E402
torch.manual_seed(0)
r = PatchSaliencyRouter(hidden_dim=32, reduction_dim=8)
with torch.no_grad():
    s = r.scorer(torch.randn(2, 64, 32) * 5.0)   # large inputs: probe the extremes
in_unit = bool((s > 0.0).all() and (s < 1.0).all())
consumers_need_prob = ("smooth_l1_loss(mean_score" in loss_src
                       and "clamped_scores = scores.clamp" in loss_src)
check("E RANGE", in_unit and consumers_need_prob,
      f"router scores in ({float(s.min()):.4f}, {float(s.max()):.4f}) subset (0,1); "
      f"loss.py still reads them as a probability (sparsity+entropy): {consumers_need_prob}")

# ------------------------------------------------------------------------ F  PARITY
gen_src = open(GEN, encoding="utf-8").read()


def sal_line(s):
    m = re.search(r"^\s*_sal\s*=.*$", s, re.M)
    return re.sub(r"\s+", " ", m.group(0)).strip() if m else None


nb_line, gen_line = sal_line(nb_src), sal_line(gen_src)
check("F PARITY", nb_line is not None and nb_line == gen_line,
      f"notebook and generator agree on the loss line"
      if nb_line == gen_line else
      f"DIVERGED -- regenerating would revert the notebook.\n"
      f"           notebook : {nb_line}\n           generator: {gen_line}")

# ------------------------------------------------------------------------- verdict
print()
print("=" * 78)
failed = [n for n, ok, _ in results if not ok]
print(f"{len(results) - len(failed)}/{len(results)} passed"
      + (f" -- FAILING: {', '.join(failed)}" if failed else " -- all clear"))
print("=" * 78)
raise SystemExit(1 if failed else 0)
